/// Hard resource limits applied while parsing and rendering.
///
/// Defaults allow at least 5x the observed fixture usage, or 4x for canvas
/// storage, which scales with output area. Exceeding a limit returns
/// [`crate::Error::LimitExceeded`].
#[derive(Debug, Clone, Copy)]
pub struct Limits {
  /// Maximum input size in bytes.
  pub max_input_bytes: usize,
  /// Maximum JSON nesting depth (objects + arrays combined).
  pub max_nesting_depth: usize,
  /// Maximum number of layers across the composition and all precomps.
  pub max_layers: usize,
  /// Maximum number of shape elements in a single layer.
  pub max_shapes_per_layer: usize,
  /// Maximum number of paint elements in a single layer.
  pub max_paints_per_layer: usize,
  /// Maximum cumulative geometry-source items observed by paints in one layer.
  pub max_paint_source_items_per_layer: usize,
  /// Maximum focal radial gradient paints in one layer.
  pub max_focal_radial_gradients_per_layer: usize,
  /// Maximum focal radial gradient paints after precomp reference expansion.
  pub max_focal_radial_gradient_expansion: usize,
  /// Maximum shape layers containing at least one retained paint.
  pub max_painted_shape_layers: usize,
  /// Maximum retained solid layers across root and asset layers.
  pub max_solid_layers: usize,
  /// Maximum keyframes for a single animated property.
  pub max_keyframes: usize,
  /// Maximum cumulative heap bytes cloned for inherited keyframe values.
  pub max_inherited_keyframe_bytes: usize,
  /// Maximum authored vertices in a single path or mask.
  pub max_path_points: usize,
  /// Maximum absolute authored coordinate/tangent magnitude in paths.
  pub max_path_coordinate_abs: f32,
  /// Maximum masks in a single layer.
  pub max_masks_per_layer: usize,
  /// Maximum retained masks across root and asset layers.
  pub max_masks: usize,
  /// Maximum authored vertices in a single mask path.
  pub max_mask_path_points: usize,
  /// Maximum dash entries in a single stroke.
  pub max_dash_elements: usize,
  /// Maximum dashed strokes in one shape group.
  pub max_dashed_strokes_per_group: usize,
  /// Maximum gradient strokes in one shape group.
  pub max_gradient_strokes_per_group: usize,
  /// Maximum source segment span before a round-join dashed stroke in one group.
  pub max_dashed_path_segment_span: f32,
  /// Maximum floats retained in a single gradient stop table.
  pub max_gradient_stop_values: usize,
  /// Maximum Fitzpatrick metadata entries parsed when requested by options.
  pub max_fitz_entries: usize,
  /// Maximum cumulative parser allocation capacity, including discarded data.
  pub max_parse_bytes: usize,
  /// Maximum authored gradient strokes after expanding referenced precomps.
  pub max_expanded_gradient_strokes: usize,
  /// Maximum expanded precomp-layer references in the asset graph.
  pub max_precomp_expansion: usize,
  /// Maximum parent-chain depth in one layer list.
  pub max_parent_chain_depth: usize,
  /// Maximum sum of parent-chain depths in one layer list.
  pub max_parent_chain_total_depth: usize,
  /// Maximum generated polystar points.
  pub max_polystar_points: f32,
  /// Maximum copies for a single repeater.
  pub max_repeater_copies: f32,
  /// Maximum round-corners modifiers in one layer.
  pub max_round_corners_per_layer: usize,
  /// Maximum trim modifiers in one layer.
  pub max_trims_per_layer: usize,
  /// Maximum estimated dash pieces generated by one shape group.
  pub max_dashed_piece_estimate_per_group: usize,
  /// Maximum compounded repeater copies in one shape group.
  pub max_repeater_product_per_group: usize,
  /// Maximum number of assets (precomps).
  pub max_assets: usize,
  /// Maximum composition width/height in points, and render size in pixels.
  pub max_dimension: u32,
  /// Maximum generated geometry points charged cumulatively per frame.
  pub max_render_points: usize,
  /// Maximum cumulative dash output allocation estimate per frame, in bytes.
  pub max_render_dash_bytes: usize,
  /// Maximum estimated pixel visits per frame at 64x64 or smaller.
  /// Larger outputs scale this allowance proportionally to canvas area.
  /// Counts covered pixels equally for every paint, including cached replay.
  pub max_render_pixels: usize,
  /// Maximum canvas-dependent scratch allocation estimate at 720x720, in bytes.
  /// Other output sizes scale this allowance proportionally to canvas area.
  pub max_render_bytes: usize,
}

impl Default for Limits {
  fn default() -> Self {
    Self {
      max_input_bytes: 16 << 20, // 16 MiB
      max_nesting_depth: 175,
      max_layers: 2_720,
      max_shapes_per_layer: 20_480,
      max_paints_per_layer: 5_120,
      max_paint_source_items_per_layer: 5_120,
      max_focal_radial_gradients_per_layer: 175,
      max_focal_radial_gradient_expansion: 850,
      max_painted_shape_layers: 2_715,
      max_solid_layers: 256,
      max_keyframes: 2048,
      max_inherited_keyframe_bytes: 8 << 20,
      max_path_points: 4_355,
      max_path_coordinate_abs: 165_389.0,
      max_masks_per_layer: 16,
      max_masks: 256,
      max_mask_path_points: 128,
      max_dash_elements: 32,
      max_dashed_strokes_per_group: 128,
      max_gradient_strokes_per_group: 45,
      max_dashed_path_segment_span: 10_110.0,
      max_gradient_stop_values: 1_860,
      max_fitz_entries: 20,
      max_parse_bytes: 43_681_460,
      max_expanded_gradient_strokes: 6_645,
      max_precomp_expansion: 18_005,
      max_parent_chain_depth: 128,
      max_parent_chain_total_depth: 16_384,
      max_polystar_points: 128.0,
      max_repeater_copies: 64.0,
      max_round_corners_per_layer: 8,
      max_trims_per_layer: 360,
      max_dashed_piece_estimate_per_group: 6_105,
      max_repeater_product_per_group: 4096,
      max_assets: 256,
      max_dimension: 8192,
      max_render_points: 3_620_695,
      max_render_dash_bytes: 15_825_600,
      max_render_pixels: 64 * 1024 * 1024,
      max_render_bytes: 116_121_600, // 4x measured 720px peak; scales with output area.
    }
  }
}
